import { type Lang, type Product, type Bundle, type PolicySection } from "@/types";

// ─── Products ────────────────────────────────────────────────────
export const defaultProducts: Product[] = [
  {
    code: "R001", category: "restaurant", price: 0, image: "/assets/thumb-restaurant.png",
    title: { zh: "简约桌号牌 1-5", en: "Simple Table Number Sign 1-5", ja: "シンプル卓番サイン 1-5", ko: "심플 테이블 번호 사인 1-5" },
    meta: { zh: "适合餐厅和咖啡店的免支撑 PLA 桌号牌。", en: "No-support PLA table signs for restaurants and cafes.", ja: "レストランやカフェ向けのサポート不要PLA卓番サイン。", ko: "레스토랑과 카페용 서포트 없는 PLA 테이블 번호 사인." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "freePrice", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "R003", category: "restaurant", price: 0, image: "/assets/thumb-restaurant.png",
    title: { zh: "二维码桌牌", en: "QR Code Table Sign", ja: "QRコード卓上サイン", ko: "QR 코드 테이블 사인" },
    meta: { zh: "适合菜单、点餐和促销链接的小型桌面支架。", en: "Small counter-friendly holder for menus, ordering, and promos.", ja: "メニュー、注文、プロモーション用の小型スタンド。", ko: "메뉴, 주문, 프로모션 링크용 소형 테이블 홀더." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "freePrice", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "R002", category: "restaurant", price: 4.99, image: "/assets/thumb-restaurant.png",
    title: { zh: "现代桌号套装 1-50", en: "Modern Table Number Set 1-50", ja: "モダン卓番セット 1-50", ko: "모던 테이블 번호 세트 1-50" },
    meta: { zh: "完整数字套装，适合低成本批量打印。", en: "Complete printable number set with clean modern styling.", ja: "すっきりした現代的な番号セット。", ko: "깔끔한 스타일의 전체 번호 출력 세트." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "sortFeatured", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "R004", category: "restaurant", price: 4.99, image: "/assets/thumb-restaurant.png",
    title: { zh: "高级二维码支架包", en: "Premium QR Code Holder Pack", ja: "プレミアムQRホルダーパック", ko: "프리미엄 QR 코드 홀더 팩" },
    meta: { zh: "菜单、支付、评价链接等多种支架样式。", en: "Multiple holder styles for menus, payment, and review links.", ja: "メニュー、決済、レビューリンク向けの複数スタイル。", ko: "메뉴, 결제, 리뷰 링크용 다양한 홀더 스타일." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "STL", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "R005", category: "restaurant", price: 2.99, image: "/assets/thumb-restaurant.png",
    title: { zh: "菜单展示架", en: "Menu Stand", ja: "メニュースタンド", ko: "메뉴 스탠드" },
    meta: { zh: "稳定、快速、低成本打印的菜单支架。", en: "A stable menu stand designed for quick low-cost printing.", ja: "短時間・低コストで印刷できる安定したスタンド。", ko: "빠르고 저렴하게 출력할 수 있는 안정적인 메뉴 스탠드." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "STL", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "B001", category: "party", price: 0, image: "/assets/thumb-party.png",
    title: { zh: "简约生日蛋糕插牌", en: "Simple Happy Birthday Cake Topper", ja: "シンプル誕生日ケーキトッパー", ko: "심플 생일 케이크 토퍼" },
    meta: { zh: "适合家庭和派对布置的易打印插牌。", en: "Easy printable topper for party decorators and families.", ja: "家庭やパーティー装飾向けの印刷しやすいトッパー。", ko: "가족과 파티 장식에 쓰기 쉬운 출력용 토퍼." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "freePrice", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "B003", category: "party", price: 3.99, image: "/assets/thumb-party.png",
    title: { zh: "数字蛋糕插牌 0-9", en: "Number Cake Topper 0-9", ja: "数字ケーキトッパー 0-9", ko: "숫자 케이크 토퍼 0-9" },
    meta: { zh: "生日和纪念日可复用的数字套装。", en: "Reusable number set for birthday and anniversary cakes.", ja: "誕生日や記念日ケーキに使える数字セット。", ko: "생일과 기념일 케이크용 재사용 숫자 세트." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "catParty", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "B004", category: "party", price: 0, image: "/assets/thumb-party.png",
    title: { zh: "派对杯姓名牌", en: "Party Cup Name Tag", ja: "パーティーカップ名札", ko: "파티 컵 이름표" },
    meta: { zh: "适合杯子、伴手礼和餐桌布置的快速打印标签。", en: "Fast-print tags for party cups, favors, and table settings.", ja: "カップ、ギフト、テーブル用の短時間印刷タグ。", ko: "컵, 답례품, 테이블 세팅용 빠른 출력 태그." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "freePrice", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "B010", category: "party", price: 9.99, image: "/assets/thumb-party.png",
    title: { zh: "派对装饰套装", en: "Party Decoration Pack", ja: "パーティー装飾パック", ko: "파티 장식 팩" },
    meta: { zh: "蛋糕插牌、桌牌、礼品标签和拍照道具。", en: "Cake toppers, signs, favor tags, and photo booth props.", ja: "ケーキトッパー、サイン、タグ、撮影小物。", ko: "케이크 토퍼, 사인, 선물 태그, 포토 부스 소품." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "bundleLabel", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "D001", category: "desk", price: 0, image: "/assets/thumb-desk.png",
    title: { zh: "简约手机支架", en: "Simple Phone Stand", ja: "シンプルスマホスタンド", ko: "심플 폰 스탠드" },
    meta: { zh: "适合手机和平板的紧凑桌面支架。", en: "Compact desktop phone stand for phones and small tablets.", ja: "スマホや小型タブレット向けのコンパクトスタンド。", ko: "휴대폰과 소형 태블릿용 컴팩트 데스크 스탠드." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "freePrice", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "D003", category: "desk", price: 0, image: "/assets/thumb-desk.png",
    title: { zh: "线夹套装", en: "Cable Clip Set", ja: "ケーブルクリップセット", ko: "케이블 클립 세트" },
    meta: { zh: "多种尺寸桌面线夹，适合 PLA 快速打印。", en: "Desk cable clips in multiple sizes for quick PLA printing.", ja: "複数サイズのデスク用ケーブルクリップ。", ko: "빠른 PLA 출력용 다양한 크기의 케이블 클립." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "freePrice", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "D002", category: "desk", price: 4.99, image: "/assets/thumb-desk.png",
    title: { zh: "高级可调手机支架", en: "Premium Adjustable Phone Stand", ja: "プレミアム調整式スマホスタンド", ko: "프리미엄 조절식 폰 스탠드" },
    meta: { zh: "角度可调升级款，可选择商业授权。", en: "Upgraded stand with adjustable angle and commercial license option.", ja: "角度調整可能な上位版、商用オプションあり。", ko: "각도 조절이 가능한 업그레이드 스탠드, 상업용 옵션 포함." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "sortFeatured", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "D004", category: "desk", price: 3.99, image: "/assets/thumb-desk.png",
    title: { zh: "耳机支架", en: "Headphone Stand", ja: "ヘッドホンスタンド", ko: "헤드폰 스탠드" },
    meta: { zh: "适合游戏桌和办公室的立式耳机支架。", en: "Clean vertical headphone stand for gaming and office desks.", ja: "ゲームデスクやオフィス向けの縦型スタンド。", ko: "게임 및 사무용 데스크에 어울리는 세로형 헤드폰 스탠드." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "STL", formats: ["stl", "3mf"], difficulty: "easy",
  },
  {
    code: "D007", category: "desk", price: 2.99, image: "/assets/thumb-desk.png",
    title: { zh: "产品展示架", en: "Product Display Stand", ja: "商品ディスプレイスタンド", ko: "제품 디스플레이 스탠드" },
    meta: { zh: "适合卡片、商品和价格标签的小商家展示架。", en: "Small business display stand for cards, products, and pricing.", ja: "カード、商品、価格表示に使える小規模店舗向けスタンド。", ko: "카드, 제품, 가격표에 쓰는 소상공인용 디스플레이 스탠드." },
    stats: { zh: "可编辑商品", en: "Editable product", ja: "編集可能な商品", ko: "수정 가능한 상품" },
    tag: "catDesk", formats: ["stl", "3mf"], difficulty: "easy",
  },
];

// ─── Bundles ─────────────────────────────────────────────────────
export const defaultBundles: Bundle[] = [
  {
    price: 9.99, image: "/assets/thumb-bundle.png",
    title: { zh: "餐厅启动套装", en: "Restaurant Starter Pack", ja: "レストランスターターパック", ko: "레스토랑 스타터 팩" },
    description: { zh: "桌号、二维码支架、预留牌和菜单架，适合咖啡店和小餐厅。", en: "Table numbers, QR holders, reserved signs, and menu stands for cafes and small restaurants.", ja: "卓番、QRホルダー、予約席サイン、メニュースタンドのセット。", ko: "테이블 번호, QR 홀더, 예약 사인, 메뉴 스탠드 구성." },
  },
  {
    price: 14.99, image: "/assets/thumb-party.png",
    title: { zh: "生日派对套装", en: "Birthday Party Pack", ja: "誕生日パーティーパック", ko: "생일 파티 팩" },
    description: { zh: "蛋糕插牌、杯子标签、数字插牌、礼品标签和派对钥匙扣模板。", en: "Cake toppers, cup tags, number toppers, gift tags, and party favor keychain templates.", ja: "ケーキトッパー、カップタグ、数字トッパー、ギフトタグ。", ko: "케이크 토퍼, 컵 태그, 숫자 토퍼, 선물 태그 구성." },
  },
  {
    price: 19.99, image: "/assets/thumb-desk.png",
    title: { zh: "桌面商业展示套装", en: "Desk Setup Business Pack", ja: "デスク・店舗展示パック", ko: "데스크 비즈니스 디스플레이 팩" },
    description: { zh: "手机支架、线夹、产品展示架、价格牌和收纳模型。", en: "Phone stands, cable clips, product display stands, price holders, and organizer files.", ja: "スマホスタンド、クリップ、商品スタンド、価格札ホルダー。", ko: "폰 스탠드, 케이블 클립, 제품 스탠드, 가격표 홀더 구성." },
  },
];

// ─── i18n Strings ────────────────────────────────────────────────
type UIStrings = Record<string, string>;

export const ui: Record<Lang, UIStrings> = {
  zh: {
    pageTitle: "PrintHub | 3D 打印模型下载平台",
    brandSub: "实用模型下载",
    navHome: "首页", navFree: "免费模型", navCategories: "分类", navCatalog: "模型库",
    navMemberships: "会员点数", navAccount: "用户中心", navBundles: "套装",
    navLicense: "授权", navOperations: "运营后台", navServices: "定制服务",
    navPolicies: "政策", navAdmin: "后台管理",
    sidebarTitle: "90 天 MVP", sidebarCopy: "先用 30 个模型验证下载、支付和转化闭环。",
    searchLabel: "搜索模型", searchPlaceholder: "搜索 QR 牌、蛋糕插牌、手机支架...",
    searchButton: "搜索", languageLabel: "语言", cart: "购物车",
    heroEyebrow: "STL / 3MF 数字下载",
    heroTitle: "为商店、派对和桌面场景准备的可打印模型。",
    heroSubtitle: "让每一个创意都能快速变成现实",
    heroCopy: "用免费模型引流，用低价单品和套装转化，再通过商业授权服务打印农场和小卖家。",
    heroPrimary: "领取免费模型", heroSecondary: "浏览模型库",
    metricModels: "首批模型", metricFree: "免费引流款", metricBundles: "启动套装", metricLicense: "商业授权",
    freeEyebrow: "免费模型漏斗", freeTitle: "先送出真正有用的文件，再推荐完整套装。",
    freeCardTitle: "免费启动文件", freeCardCopy: "下载示例 STL，并加入首发名单领取 10 个实用免费模型。",
    emailLabel: "邮箱地址", sendDownload: "发送下载链接",
    packTitle: "下载包内容",
    packItem1: "STL 和 3MF 文件", packItem2: "PLA 打印说明",
    packItem3: "个人使用授权", packItem4: "推荐付费套装",
    catEyebrow: "首批 3 个分类", catTitle: "90 天内聚焦的模型集合。",
    catRestaurant: "餐厅与咖啡店", catParty: "生日与派对", catDesk: "桌面与展示",
    catalogEyebrow: "STL 模型库", catalogTitle: "来自首批 30 个模型计划的上架产品。",
    filterAll: "全部", filterRestaurant: "餐厅", filterParty: "派对", filterDesk: "桌面",
    filterAllPrices: "全部价格", filterFree: "免费", filterPaid: "付费",
    filterAllFormats: "全部格式", filterAllDifficulty: "全部难度",
    difficultyEasy: "新手友好", difficultyMedium: "进阶打印",
    sortLabel: "排序", sortFeatured: "推荐", sortLow: "价格从低到高",
    sortHigh: "价格从高到低", sortName: "名称",
    emptyState: "暂无匹配模型。",
    membershipEyebrow: "收入模式", membershipTitle: "单品购买、会员订阅和点数充值可以一起存在。",
    planSingle: "单品购买", planSingleCopy: "适合低价模型和套装，先跑通支付与下载闭环。",
    planMonthly: "会员订阅", planMonthlyCopy: "会员每月获得下载额度、专属折扣和商业授权优惠。",
    planPoints: "点数充值", planPointsCopy: "用户提前购买点数，用点数兑换模型、定制或打印服务。",
    accountEyebrow: "用户中心", accountTitle: "让用户可以回到网站查看已购模型、订单和授权。",
    accountPurchased: "已购模型", accountDownloads: "下载记录",
    accountFavorites: "收藏夹", accountPoints: "点数余额",
    accountLicense: "授权文件", accountOrders: "订单查询",
    opsEyebrow: "后台能力规划", opsTitle: "后期登录后台要服务上架、订单、数据和审核。",
    opsModels: "模型管理", opsModelsCopy: "上传模型、编辑价格、分类、格式、图片和授权。",
    opsBatch: "批量上架下架", opsBatchCopy: "支持批量修改状态、价格、标签和推荐位。",
    opsOrders: "订单查询", opsOrdersCopy: "查看付款、下载、退款、发票和用户联系信息。",
    opsData: "数据看板", opsDataCopy: "统计浏览、收藏、下载、转化率和热卖分类。",
    opsQuality: "人工审核", opsQualityCopy: "新模型上线前检查版权、可打印性、图片和授权说明。",
    opsAi: "AI 批量生成", opsAiCopy: "AI 可以辅助生成草稿，但必须经过人工测试和审核再上架。",
    bundleEyebrow: "提高客单价", bundleTitle: "套装把免费流量变成更明确的购买意图。",
    licenseEyebrow: "个人 / 商业", licenseTitle: "给玩家、打印农场和小卖家的清晰授权。",
    personalTitle: "个人授权",
    personal1: "用于个人 3D 打印", personal2: "可为私人项目修改文件", personal3: "不可销售打印成品",
    commercialTitle: "商业授权",
    commercial1: "可在线上或本地销售实体打印件", commercial2: "可在商品页使用产品图片", commercial3: "不可转售或分发数字文件",
    customTitle: "定制", custom1: "姓名、Logo 底座、尺寸或文字修改",
    custom2: "按复杂度报价", custom3: "可附加代打印需求",
    serviceEyebrow: "后续收入入口", serviceTitle: "定制 STL 和代打印询盘流程。",
    nameLabel: "姓名", namePlaceholder: "你的姓名",
    requestType: "需求类型", requestCustom: "定制 STL 模型",
    requestModify: "修改现有模型", requestPrint: "帮我打印", requestLicense: "商业授权报价",
    budgetLabel: "预算", budgetUnsure: "暂不确定",
    projectDetails: "项目细节", projectPlaceholder: "说明用途、尺寸、材料、截止时间，以及是否需要代打印。",
    quoteButton: "请求报价",
    policyEyebrow: "信任页面", policyTitle: "上线前必须准备的基础政策。",
    policyRefund: "退款", policyLicense: "授权", policyCopyright: "版权", policyContact: "联系",
    cartTitle: "购物车", total: "合计", checkoutDemo: "演示结账",
    freePrice: "免费", download: "下载", add: "加入", addBundle: "加入套装", remove: "移除",
    emptyCart: "购物车是空的。加入一个付费 STL 或套装来测试结账流程。",
    freePrompt: "{title} 是免费模型。请输入邮箱接收下载链接。",
    leadSuccess: "演示：免费下载链接将发送到 {email}。",
    serviceSuccess: "演示：报价请求已保存。正式上线前可连接邮箱或 CRM。",
    checkoutEmpty: "请先加入一个付费模型再测试结账。",
    checkoutSuccess: "演示结账完成。正式版本可连接 Stripe、PayPal 和数字下载邮件。",
  },
  en: {
    pageTitle: "PrintHub | 3D Model Downloads",
    brandSub: "Practical model downloads",
    navHome: "Home", navFree: "Free Models", navCategories: "Categories", navCatalog: "Catalog",
    navMemberships: "Memberships", navAccount: "Account", navBundles: "Bundles",
    navLicense: "License", navOperations: "Operations", navServices: "Custom Orders",
    navPolicies: "Policies", navAdmin: "Admin",
    sidebarTitle: "90-Day MVP", sidebarCopy: "Validate downloads, payment, and conversion with the first 30 models.",
    searchLabel: "Search models", searchPlaceholder: "Search QR sign, cake topper, phone stand...",
    searchButton: "Search", languageLabel: "Language", cart: "Cart",
    heroEyebrow: "STL / 3MF digital downloads",
    heroTitle: "Print-ready models for shops, parties, and desk setups.",
    heroSubtitle: "Turn every idea into reality, fast",
    heroCopy: "Use free models for traffic, low-cost products and bundles for conversion, and commercial licenses for print farms.",
    heroPrimary: "Get free models", heroSecondary: "Browse catalog",
    metricModels: "Launch Models", metricFree: "Free Funnel Files", metricBundles: "Starter Bundles", metricLicense: "Commercial License",
    freeEyebrow: "Free download funnel", freeTitle: "Give away useful files, then recommend the full pack.",
    freeCardTitle: "Free starter files", freeCardCopy: "Download a sample STL and join the launch list for 10 free practical models.",
    emailLabel: "Email address", sendDownload: "Send download",
    packTitle: "Download pack contents",
    packItem1: "STL and 3MF files", packItem2: "PLA print instructions",
    packItem3: "Personal use license", packItem4: "Recommended paid bundles",
    catEyebrow: "First 3 Categories", catTitle: "Focused model collections for the first 90 days.",
    catRestaurant: "Restaurant & Café", catParty: "Birthday & Party", catDesk: "Desk & Display",
    catalogEyebrow: "STL Catalog", catalogTitle: "Launch products from the first 30-model plan.",
    filterAll: "All", filterRestaurant: "Restaurant", filterParty: "Party", filterDesk: "Desk",
    filterAllPrices: "All Prices", filterFree: "Free", filterPaid: "Paid",
    filterAllFormats: "All Formats", filterAllDifficulty: "All Difficulty",
    difficultyEasy: "Beginner", difficultyMedium: "Advanced",
    sortLabel: "Sort", sortFeatured: "Featured", sortLow: "Price: Low to High",
    sortHigh: "Price: High to Low", sortName: "Name",
    emptyState: "No matching models found.",
    membershipEyebrow: "Revenue Model", membershipTitle: "One-time purchases, memberships, and point packs can coexist.",
    planSingle: "Single Purchase", planSingleCopy: "Best for low-price models and bundles while the payment and download loop is being proven.",
    planMonthly: "Monthly Membership", planMonthlyCopy: "Members receive monthly download credits, exclusive discounts, and commercial-license perks.",
    planPoints: "Point Packs", planPointsCopy: "Prepaid points for models, custom orders, or print services.",
    accountEyebrow: "Account Dashboard", accountTitle: "Let users return to view purchased models, orders, and licenses.",
    accountPurchased: "Purchased", accountDownloads: "Downloads",
    accountFavorites: "Favorites", accountPoints: "Points",
    accountLicense: "Licenses", accountOrders: "Orders",
    opsEyebrow: "Backend Roadmap", opsTitle: "The future admin should support catalog, order, analytics, and review work.",
    opsModels: "Model Management", opsModelsCopy: "Upload models, edit prices, categories, formats, images, and licenses.",
    opsBatch: "Batch Operations", opsBatchCopy: "Batch update status, price, tags, and featured positions.",
    opsOrders: "Order Lookup", opsOrdersCopy: "View payments, downloads, refunds, invoices, and customer contact details.",
    opsData: "Analytics Dashboard", opsDataCopy: "Track views, favorites, downloads, conversion, and top categories.",
    opsQuality: "Manual Review", opsQualityCopy: "Check copyright, printability, images, and license before listing new models.",
    opsAi: "AI Batch Generation", opsAiCopy: "AI can help draft products, but must pass human review and test prints before listing.",
    bundleEyebrow: "Increase Average Order", bundleTitle: "Bundles turn free traffic into paid checkout intent.",
    licenseEyebrow: "Personal / Commercial", licenseTitle: "Clear licensing for hobby users, print farms, and small sellers.",
    personalTitle: "Personal License",
    personal1: "For personal 3D printing", personal2: "Modify for private projects", personal3: "May not sell printed items",
    commercialTitle: "Commercial License",
    commercial1: "Sell physical prints online or locally", commercial2: "Use product images in listings", commercial3: "May not resell or distribute digital files",
    customTitle: "Custom", custom1: "Name, logo base, size, or text modifications",
    custom2: "Priced by complexity", custom3: "Print-for-me service available",
    serviceEyebrow: "Future Revenue Stream", serviceTitle: "Custom STL and print-this-for-me inquiry flow.",
    nameLabel: "Name", namePlaceholder: "Your name",
    requestType: "Request type", requestCustom: "Custom STL model",
    requestModify: "Modify existing model", requestPrint: "Print for me", requestLicense: "Commercial license quote",
    budgetLabel: "Budget", budgetUnsure: "Not sure",
    projectDetails: "Project details", projectPlaceholder: "Describe the use case, size, material, deadline, and whether you need printing service.",
    quoteButton: "Request quote",
    policyEyebrow: "Trust Pages", policyTitle: "Essential policies to prepare before launch.",
    policyRefund: "Refund", policyLicense: "License", policyCopyright: "Copyright", policyContact: "Contact",
    cartTitle: "Your cart", total: "Total", checkoutDemo: "Checkout demo",
    freePrice: "Free", download: "Download", add: "Add", addBundle: "Add bundle", remove: "Remove",
    emptyCart: "Your cart is empty. Add a paid STL or bundle to test the checkout flow.",
    freePrompt: "{title} is free. Enter an email to receive the download link.",
    leadSuccess: "Demo: the free STL download link would be sent to {email}.",
    serviceSuccess: "Demo: quote request saved. Connect this form to email or a CRM before launch.",
    checkoutEmpty: "Add a paid model before testing checkout.",
    checkoutSuccess: "Demo checkout complete. A real build would connect Stripe, PayPal, and digital delivery email.",
  },
  ja: {
    pageTitle: "PrintHub | 3Dモデルダウンロード",
    brandSub: "実用モデルダウンロード",
    navHome: "ホーム", navFree: "無料モデル", navCategories: "カテゴリ", navCatalog: "モデル一覧",
    navMemberships: "会員プラン", navAccount: "アカウント", navBundles: "セット",
    navLicense: "ライセンス", navOperations: "運営管理", navServices: "カスタム注文",
    navPolicies: "ポリシー", navAdmin: "管理画面",
    sidebarTitle: "90日 MVP", sidebarCopy: "最初の30モデルでダウンロード・支払い・転換を検証。",
    searchLabel: "モデル検索", searchPlaceholder: "QRサイン、ケーキトッパー、スマホスタンドを検索...",
    searchButton: "検索", languageLabel: "言語", cart: "カート",
    heroEyebrow: "STL / 3MF デジタルダウンロード",
    heroTitle: "店舗、パーティー、デスク向けのプリント対応モデル。",
    heroSubtitle: "すべてのアイデアを素早く現実に",
    heroCopy: "無料モデルで集客し、低価格モデルとセットで転換、商用ライセンスで印刷販売者にも対応します。",
    heroPrimary: "無料モデルを入手", heroSecondary: "モデルを見る",
    metricModels: "初期モデル", metricFree: "無料配布", metricBundles: "スターターセット", metricLicense: "商用ライセンス",
    freeEyebrow: "無料モデル", freeTitle: "役立つファイルを配布し、フルセットへつなげます。",
    freeCardTitle: "無料スターターファイル", freeCardCopy: "サンプルSTLをダウンロードし、10点の無料モデルを受け取る。",
    emailLabel: "メールアドレス", sendDownload: "リンクを送信",
    packTitle: "ダウンロード内容",
    packItem1: "STL / 3MF ファイル", packItem2: "PLA 印刷ガイド",
    packItem3: "個人利用ライセンス", packItem4: "おすすめ有料セット",
    catEyebrow: "3つのカテゴリ", catTitle: "90日間で注力するモデルコレクション。",
    catRestaurant: "レストラン・カフェ", catParty: "誕生日・パーティー", catDesk: "デスク・ディスプレイ",
    catalogEyebrow: "STL カタログ", catalogTitle: "最初の30モデル計画からの商品。",
    filterAll: "すべて", filterRestaurant: "レストラン", filterParty: "パーティー", filterDesk: "デスク",
    filterAllPrices: "すべての価格", filterFree: "無料", filterPaid: "有料",
    filterAllFormats: "すべての形式", filterAllDifficulty: "すべての難易度",
    difficultyEasy: "初心者向け", difficultyMedium: "上級者向け",
    sortLabel: "並び替え", sortFeatured: "おすすめ", sortLow: "価格：安い順",
    sortHigh: "価格：高い順", sortName: "名前順",
    emptyState: "該当するモデルがありません。",
    membershipEyebrow: "収益モデル", membershipTitle: "単品購入、月額会員、ポイントチャージを共存可能。",
    planSingle: "単品購入", planSingleCopy: "低価格モデルとセットで支払い・ダウンロードの流れを検証。",
    planMonthly: "月額会員", planMonthlyCopy: "会員は毎月のダウンロード枠、割引、商用ライセンス特典を受け取れます。",
    planPoints: "ポイントチャージ", planPointsCopy: "事前購入したポイントでモデルやカスタム注文に交換。",
    accountEyebrow: "ユーザーセンター", accountTitle: "購入済みモデル、注文、ライセンスを確認できるように。",
    accountPurchased: "購入済み", accountDownloads: "ダウンロード履歴",
    accountFavorites: "お気に入り", accountPoints: "ポイント残高",
    accountLicense: "ライセンス", accountOrders: "注文履歴",
    opsEyebrow: "管理機能計画", opsTitle: "将来の管理画面は商品管理、注文、分析、審査をサポート。",
    opsModels: "モデル管理", opsModelsCopy: "モデルのアップロード、価格・カテゴリ・形式・画像・ライセンスの編集。",
    opsBatch: "一括操作", opsBatchCopy: "ステータス、価格、タグ、おすすめ設定を一括更新。",
    opsOrders: "注文検索", opsOrdersCopy: "支払い、ダウンロード、返金、請求書、顧客情報の確認。",
    opsData: "データ分析", opsDataCopy: "閲覧数、お気に入り、ダウンロード数、転換率、人気カテゴリを追跡。",
    opsQuality: "人手審査", opsQualityCopy: "新規モデル公開前に著作権、印刷品質、画像、ライセンスを確認。",
    opsAi: "AI一括生成", opsAiCopy: "AIで下書きを生成できますが、公開前には必ず人間がテストと審査を行います。",
    bundleEyebrow: "客単価向上", bundleTitle: "セット商品で無料流入を購入意欲に変えます。",
    licenseEyebrow: "個人 / 商用", licenseTitle: "ユーザー、印刷販売者、小規模ショップ向けの明確なライセンス。",
    personalTitle: "個人ライセンス",
    personal1: "個人での3Dプリント用", personal2: "プライベートプロジェクト用に改変可", personal3: "印刷物の販売不可",
    commercialTitle: "商用ライセンス",
    commercial1: "オンライン・実店舗での印刷物販売可", commercial2: "商品ページでの画像使用可", commercial3: "デジタルファイルの再販・配布不可",
    customTitle: "カスタム", custom1: "名前、ロゴ台座、サイズ、テキストの修正",
    custom2: "複雑さに応じた見積もり", custom3: "プリント代行オプションあり",
    serviceEyebrow: "将来の収益源", serviceTitle: "カスタムSTLとプリント代行の問い合わせ。",
    nameLabel: "名前", namePlaceholder: "お名前",
    requestType: "依頼種類", requestCustom: "カスタムSTLモデル",
    requestModify: "既存モデルの修正", requestPrint: "プリント代行", requestLicense: "商用ライセンス見積",
    budgetLabel: "予算", budgetUnsure: "未定",
    projectDetails: "プロジェクト詳細", projectPlaceholder: "用途、サイズ、素材、期限、プリント代行の必要有無を書いてください。",
    quoteButton: "見積もり依頼",
    policyEyebrow: "信頼ページ", policyTitle: "公開前に準備すべき基本ポリシー。",
    policyRefund: "返金", policyLicense: "ライセンス", policyCopyright: "著作権", policyContact: "連絡先",
    cartTitle: "カート", total: "合計", checkoutDemo: "デモ決済",
    freePrice: "無料", download: "ダウンロード", add: "追加", addBundle: "セット追加", remove: "削除",
    emptyCart: "カートは空です。有料STLかセットを追加して決済をテストしてください。",
    freePrompt: "{title} は無料です。ダウンロードリンクを受け取るメールアドレスを入力してください。",
    leadSuccess: "デモ：無料ダウンロードリンクが {email} に送信されます。",
    serviceSuccess: "デモ：見積依頼を保存しました。正式版ではメールやCRMに接続してください。",
    checkoutEmpty: "決済テストの前に有料モデルを追加してください。",
    checkoutSuccess: "デモ決済完了。正式版ではStripe、PayPal、デジタル配信メールに接続します。",
  },
  ko: {
    pageTitle: "PrintHub | 3D 모델 다운로드",
    brandSub: "실용 모델 다운로드",
    navHome: "홈", navFree: "무료 모델", navCategories: "카테고리", navCatalog: "모델 목록",
    navMemberships: "회원 포인트", navAccount: "내 계정", navBundles: "번들",
    navLicense: "라이선스", navOperations: "운영 관리", navServices: "맞춤 주문",
    navPolicies: "정책", navAdmin: "관리자",
    sidebarTitle: "90일 MVP", sidebarCopy: "첫 30개 모델로 다운로드, 결제, 전환을 검증합니다.",
    searchLabel: "모델 검색", searchPlaceholder: "QR 사인, 케이크 토퍼, 폰 스탠드 검색...",
    searchButton: "검색", languageLabel: "언어", cart: "장바구니",
    heroEyebrow: "STL / 3MF 디지털 다운로드",
    heroTitle: "매장, 파티, 데스크용 바로 출력 가능한 모델.",
    heroSubtitle: "모든 아이디어를 빠르게 현실로",
    heroCopy: "무료 모델로 유입을 만들고, 저가 상품과 번들로 전환하며, 상업용 라이선스로 출력 판매자까지 대응합니다.",
    heroPrimary: "무료 모델 받기", heroSecondary: "모델 보기",
    metricModels: "초기 모델", metricFree: "무료 유입용", metricBundles: "스타터 번들", metricLicense: "상업 라이선스",
    freeEyebrow: "무료 모델", freeTitle: "실제로 유용한 파일을 제공하고 전체 팩을 추천합니다.",
    freeCardTitle: "무료 스타터 파일", freeCardCopy: "샘플 STL을 다운로드하고 10개의 무료 실용 모델을 받으세요.",
    emailLabel: "이메일 주소", sendDownload: "링크 전송",
    packTitle: "다운로드 내용",
    packItem1: "STL / 3MF 파일", packItem2: "PLA 출력 가이드",
    packItem3: "개인 사용 라이선스", packItem4: "추천 유료 번들",
    catEyebrow: "3개 카테고리", catTitle: "90일 동안 집중할 모델 컬렉션.",
    catRestaurant: "레스토랑 & 카페", catParty: "생일 & 파티", catDesk: "데스크 & 디스플레이",
    catalogEyebrow: "STL 카탈로그", catalogTitle: "첫 30개 모델 계획의 출시 상품.",
    filterAll: "전체", filterRestaurant: "레스토랑", filterParty: "파티", filterDesk: "데스크",
    filterAllPrices: "전체 가격", filterFree: "무료", filterPaid: "유료",
    filterAllFormats: "전체 형식", filterAllDifficulty: "전체 난이도",
    difficultyEasy: "초보자용", difficultyMedium: "고급자용",
    sortLabel: "정렬", sortFeatured: "추천순", sortLow: "낮은 가격순",
    sortHigh: "높은 가격순", sortName: "이름순",
    emptyState: "일치하는 모델이 없습니다.",
    membershipEyebrow: "수익 모델", membershipTitle: "단품 구매, 월간 회원, 포인트 충전을 함께 운영할 수 있습니다.",
    planSingle: "단품 구매", planSingleCopy: "저렴한 모델과 번들로 결제 및 다운로드 흐름을 검증합니다.",
    planMonthly: "월간 회원", planMonthlyCopy: "회원은 매월 다운로드 크레딧, 할인, 상업용 라이선스 혜택을 받습니다.",
    planPoints: "포인트 충전", planPointsCopy: "미리 구매한 포인트로 모델, 맞춤 주문, 출력 서비스를 이용합니다.",
    accountEyebrow: "사용자 센터", accountTitle: "사용자가 구매한 모델, 주문, 라이선스를 확인할 수 있도록 합니다.",
    accountPurchased: "구매 모델", accountDownloads: "다운로드 기록",
    accountFavorites: "즐겨찾기", accountPoints: "포인트 잔액",
    accountLicense: "라이선스", accountOrders: "주문 조회",
    opsEyebrow: "관리 기능 계획", opsTitle: "향후 관리자는 상품, 주문, 분석, 검토를 지원합니다.",
    opsModels: "모델 관리", opsModelsCopy: "모델 업로드, 가격·카테고리·형식·이미지·라이선스 편집.",
    opsBatch: "일괄 작업", opsBatchCopy: "상태, 가격, 태그, 추천 설정을 일괄 업데이트.",
    opsOrders: "주문 조회", opsOrdersCopy: "결제, 다운로드, 환불, 청구서, 고객 연락처 확인.",
    opsData: "데이터 분석", opsDataCopy: "조회수, 즐겨찾기, 다운로드, 전환율, 인기 카테고리 추적.",
    opsQuality: "수동 검토", opsQualityCopy: "신규 모델 등록 전 저작권, 출력 품질, 이미지, 라이선스 확인.",
    opsAi: "AI 일괄 생성", opsAiCopy: "AI로 초안을 생성할 수 있지만, 등록 전 반드시 사람이 테스트하고 검토해야 합니다.",
    bundleEyebrow: "객단가 향상", bundleTitle: "번들은 무료 유입을 구매 의도로 전환합니다.",
    licenseEyebrow: "개인 / 상업", licenseTitle: "취미 사용자, 출력 판매자, 소규모 판매자를 위한 명확한 라이선스.",
    personalTitle: "개인 라이선스",
    personal1: "개인 3D 프린팅용", personal2: "개인 프로젝트용 수정 가능", personal3: "출력물 판매 불가",
    commercialTitle: "상업 라이선스",
    commercial1: "온라인·오프라인에서 출력물 판매 가능", commercial2: "상품 페이지에 제품 이미지 사용 가능", commercial3: "디지털 파일 재판매·배포 불가",
    customTitle: "맞춤 제작", custom1: "이름, 로고, 크기, 텍스트 수정",
    custom2: "복잡도에 따른 견적", custom3: "출력 대행 옵션 가능",
    serviceEyebrow: "향후 수익원", serviceTitle: "맞춤 STL 및 출력 대행 문의 흐름.",
    nameLabel: "이름", namePlaceholder: "이름",
    requestType: "요청 유형", requestCustom: "맞춤 STL 모델",
    requestModify: "기존 모델 수정", requestPrint: "출력 대행", requestLicense: "상업 라이선스 견적",
    budgetLabel: "예산", budgetUnsure: "미정",
    projectDetails: "프로젝트 상세", projectPlaceholder: "용도, 크기, 재료, 마감일, 출력 대행 필요 여부를 적어주세요.",
    quoteButton: "견적 요청",
    policyEyebrow: "신뢰 페이지", policyTitle: "출시 전 준비해야 할 기본 정책.",
    policyRefund: "환불", policyLicense: "라이선스", policyCopyright: "저작권", policyContact: "연락처",
    cartTitle: "장바구니", total: "합계", checkoutDemo: "결제 데모",
    freePrice: "무료", download: "다운로드", add: "추가", addBundle: "번들 추가", remove: "제거",
    emptyCart: "장바구니가 비어 있습니다. 유료 STL 또는 번들을 추가하여 결제 흐름을 테스트하세요.",
    freePrompt: "{title}은(는) 무료입니다. 다운로드 링크를 받을 이메일을 입력하세요.",
    leadSuccess: "데모: 무료 다운로드 링크가 {email}로 전송됩니다.",
    serviceSuccess: "데모: 견적 요청이 저장되었습니다. 출시 전 이메일이나 CRM에 연결하세요.",
    checkoutEmpty: "결제 테스트 전에 유료 모델을 추가하세요.",
    checkoutSuccess: "데모 결제 완료. 실제 버전은 Stripe, PayPal, 디지털 배송 이메일과 연결됩니다.",
  },
};

// ─── Policy Content ──────────────────────────────────────────────
export const policyCopy: Record<string, PolicySection> = {
  refund: {
    title: { zh: "退款政策", en: "Refund Policy", ja: "返金ポリシー", ko: "환불 정책" },
    body: { zh: "数字产品售出后原则上不退不换。如文件无法下载或有严重质量问题，请在 7 天内联系我们，我们将提供替换文件或退款。", en: "Digital products are non-refundable in principle. If a file cannot be downloaded or has serious quality issues, contact us within 7 days for a replacement or refund.", ja: "デジタル商品は原則返品不可です。ダウンロード不可や重大な品質問題がある場合は7日以内にご連絡ください。", ko: "디지털 상품은 원칙적으로 환불이 불가합니다. 다운로드 불가 또는 심각한 품질 문제가 있을 경우 7일 이내에 연락 주시면 교체 또는 환불해 드립니다." },
  },
  license: {
    title: { zh: "授权条款", en: "License Terms", ja: "ライセンス条項", ko: "라이선스 약관" },
    body: { zh: "所有模型均附带个人使用授权。商业授权需另行购买。严禁在未经授权的情况下转售、分发数字文件或将其上传至其他平台。", en: "All models include a personal use license. Commercial licenses must be purchased separately. Reselling, distributing digital files, or uploading to other platforms without authorization is strictly prohibited.", ja: "すべてのモデルには個人利用ライセンスが付属します。商用ライセンスは別途購入が必要です。デジタルファイルの無断転売・配布・他プラットフォームへのアップロードは禁止です。", ko: "모든 모델은 개인 사용 라이선스가 포함됩니다. 상업용 라이선스는 별도 구매가 필요합니다. 디지털 파일의 무단 재판매, 배포, 타 플랫폼 업로드는 금지됩니다." },
  },
  copyright: {
    title: { zh: "版权声明", en: "Copyright / DMCA", ja: "著作権 / DMCA", ko: "저작권 / DMCA" },
    body: { zh: "本站所有模型均为原创设计或经合法授权。如果您认为任何内容侵犯了您的版权，请通过联系表单通知我们，我们将在 48 小时内处理。", en: "All models on this site are original designs or legally licensed. If you believe any content infringes your copyright, please notify us via the contact form and we will respond within 48 hours.", ja: "当サイトの全モデルはオリジナルデザインまたは正規ライセンス品です。著作権侵害と思われる場合はお問い合わせフォームよりご連絡ください。48時間以内に対応します。", ko: "이 사이트의 모든 모델은 독창적인 디자인이거나 정식 라이선스를 받았습니다. 저작권 침해로 의심되는 콘텐츠가 있다면 문의 양식을 통해 알려주시면 48시간 이내에 처리하겠습니다." },
  },
  contact: {
    title: { zh: "联系我们", en: "Contact Us", ja: "お問い合わせ", ko: "문의하기" },
    body: { zh: "定制 STL、代打印、文件问题和商业授权都可以通过询盘表单联系。正式版本建议连接邮箱、CRM 或客服系统。", en: "Use the quote form for custom STL work, print service requests, file problems, and commercial license questions. A real launch version should connect this to email, CRM, or support system.", ja: "カスタムSTL、プリント代行、ファイル問題、商用ライセンスは問い合わせフォームから連絡できます。正式版ではメールやCRMへ接続します。", ko: "맞춤 STL, 출력 대행, 파일 문제, 상업용 라이선스는 문의 양식으로 연락할 수 있습니다. 실제 출시 버전은 이메일, CRM 또는 지원 시스템과 연결합니다." },
  },
};

// ─── Helper: get text in current language ────────────────────────
export function text(value: string | Record<Lang, string>, lang: Lang): string {
  if (typeof value === "string") return ui[lang]?.[value] || value;
  return value[lang] || value.en || value.zh || "";
}

export function t(key: string, lang: Lang): string {
  return ui[lang]?.[key] || ui.en?.[key] || key;
}

export function money(price: number, lang: Lang): string {
  if (price === 0) return t("freePrice", lang);
  return `$${price.toFixed(2)}`;
}

export function format(template: string, values: Record<string, string>): string {
  return Object.entries(values).reduce((r, [k, v]) => r.replace(`{${k}}`, v), template);
}
